mode: ours # 'baseline' or 'ours'

align:
  enable: true
  beta1: 1.0 # weight for L_plane
  beta2: 0.1 # weight for L_normal
  knn_k: 10 # number of neighbors for KNN
  knn_chunk_size: 4096 # chunk size to prevent OOM
  sigma_d: 0.01 # distance weight control
  lambda2_max: 0.5 # maximum weight for alignment loss
  warmup_iters: 10 # iterations to wait before strictly enabling align loss
  ramp_iters: 50 # iterations it takes to linearly increase to lambda2_max
